#!/bin/sh
set -eu

SERVER__PORT="${UNBOUND__SERVER__PORT:-5353}"
SERVER__USERNAME="${UNBOUND__SERVER__USERNAME:-}"
SERVER__NUM_THREADS="${UNBOUND__SERVER__NUM_THREADS:-2}"
SERVER__SO_RCVBUF="${UNBOUND__SERVER__SO_RCVBUF:-0}"
SERVER__SO_SNDBUF="${UNBOUND__SERVER__SO_SNDBUF:-0}"
SERVER__DO_NOT_QUERY_LOCALHOST="${UNBOUND__SERVER__DO_NOT_QUERY_LOCALHOST:-yes}"
SERVER__VERBOSITY="${UNBOUND__SERVER__VERBOSITY:-1}"
SERVER__LOG_QUERIES="${UNBOUND__SERVER__LOG_QUERIES:-yes}"
SERVER__USE_SYSLOG="${UNBOUND__SERVER__USE_SYSLOG:-no}"
SERVER__LOGFILE="${UNBOUND__SERVER__LOGFILE:-\"\"}"
SERVER__AUTO_TRUST_ANCHOR_FILE="${UNBOUND__SERVER__AUTO_TRUST_ANCHOR_FILE:-/var/unbound/root.key}"
SERVER__DIRECTORY="${UNBOUND__SERVER__DIRECTORY:-/var/unbound}"
SERVER__CHROOT="${UNBOUND__SERVER__CHROOT:-}"
SERVER__INTERFACE="${UNBOUND__SERVER__INTERFACE:-0.0.0.0}"
SERVER__DO_IP4="${UNBOUND__SERVER__DO_IP4:-yes}"
SERVER__DO_IP6="${UNBOUND__SERVER__DO_IP6:-no}"
SERVER__DO_UDP="${UNBOUND__SERVER__DO_UDP:-yes}"
SERVER__DO_TCP="${UNBOUND__SERVER__DO_TCP:-yes}"
SERVER__USE_CAPS_FOR_ID="${UNBOUND__SERVER__USE_CAPS_FOR_ID:-yes}"
SERVER__PREFETCH="${UNBOUND__SERVER__PREFETCH:-yes}"
SERVER__PREFETCH_KEY="${UNBOUND__SERVER__PREFETCH_KEY:-yes}"
SERVER__QNAME_MINIMISATION="${UNBOUND__SERVER__QNAME_MINIMISATION:-yes}"
SERVER__MINIMAL_RESPONSES="${UNBOUND__SERVER__MINIMAL_RESPONSES:-yes}"
SERVER__HIDE_IDENTITY="${UNBOUND__SERVER__HIDE_IDENTITY:-yes}"
SERVER__HIDE_VERSION="${UNBOUND__SERVER__HIDE_VERSION:-yes}"
SERVER__HARDEN_GLUE="${UNBOUND__SERVER__HARDEN_GLUE:-yes}"
SERVER__HARDEN_DNSSEC_STRIPPED="${UNBOUND__SERVER__HARDEN_DNSSEC_STRIPPED:-yes}"
SERVER__HARDEN_REFERRAL_PATH="${UNBOUND__SERVER__HARDEN_REFERRAL_PATH:-yes}"
SERVER__HARDEN_ALGO_DOWNGRADE="${UNBOUND__SERVER__HARDEN_ALGO_DOWNGRADE:-yes}"
SERVER__CACHE_MIN_TTL="${UNBOUND__SERVER__CACHE_MIN_TTL:-60}"
SERVER__CACHE_MAX_TTL="${UNBOUND__SERVER__CACHE_MAX_TTL:-86400}"
SERVER__MSG_CACHE_SIZE="${UNBOUND__SERVER__MSG_CACHE_SIZE:-64m}"
SERVER__RRSET_CACHE_SIZE="${UNBOUND__SERVER__RRSET_CACHE_SIZE:-64m}"
SERVER__UNWANTED_REPLY_THRESHOLD="${UNBOUND__SERVER__UNWANTED_REPLY_THRESHOLD:-10000}"
FORWARD_ZONE__FORWARD_ADDR="${UNBOUND__FORWARD_ZONE__FORWARD_ADDR:-}"
FORWARD_ZONE__NAME="${UNBOUND__FORWARD_ZONE__NAME:-.}"
FORWARD_ZONE__FORWARD_TLS_UPSTREAM="${UNBOUND__FORWARD_ZONE__FORWARD_TLS_UPSTREAM:-no}"
CONF="/etc/unbound/unbound.conf"
TEMPLATE="/etc/unbound/unbound.conf.template"

if [ -f "$TEMPLATE" ]; then
    esc() {
        printf '%s' "$1" | sed -e 's/[&|]/\\&/g'
    }

    sed \
        -e "s|__SERVER__USERNAME__|$(esc "$SERVER__USERNAME")|g" \
        -e "s|__SERVER__PORT__|$(esc "$SERVER__PORT")|g" \
        -e "s|__SERVER__NUM_THREADS__|$(esc "$SERVER__NUM_THREADS")|g" \
        -e "s|__SERVER__SO_RCVBUF__|$(esc "$SERVER__SO_RCVBUF")|g" \
        -e "s|__SERVER__SO_SNDBUF__|$(esc "$SERVER__SO_SNDBUF")|g" \
        -e "s|__SERVER__DO_NOT_QUERY_LOCALHOST__|$(esc "$SERVER__DO_NOT_QUERY_LOCALHOST")|g" \
        -e "s|__SERVER__VERBOSITY__|$(esc "$SERVER__VERBOSITY")|g" \
        -e "s|__SERVER__LOG_QUERIES__|$(esc "$SERVER__LOG_QUERIES")|g" \
        -e "s|__SERVER__USE_SYSLOG__|$(esc "$SERVER__USE_SYSLOG")|g" \
        -e "s|__SERVER__LOGFILE__|$(esc "$SERVER__LOGFILE")|g" \
        -e "s|__SERVER__AUTO_TRUST_ANCHOR_FILE__|$(esc "$SERVER__AUTO_TRUST_ANCHOR_FILE")|g" \
        -e "s|__SERVER__DIRECTORY__|$(esc "$SERVER__DIRECTORY")|g" \
        -e "s|__SERVER__CHROOT__|$(esc "$SERVER__CHROOT")|g" \
        -e "s|__SERVER__INTERFACE__|$(esc "$SERVER__INTERFACE")|g" \
        -e "s|__SERVER__DO_IP4__|$(esc "$SERVER__DO_IP4")|g" \
        -e "s|__SERVER__DO_IP6__|$(esc "$SERVER__DO_IP6")|g" \
        -e "s|__SERVER__DO_UDP__|$(esc "$SERVER__DO_UDP")|g" \
        -e "s|__SERVER__DO_TCP__|$(esc "$SERVER__DO_TCP")|g" \
        -e "s|__SERVER__USE_CAPS_FOR_ID__|$(esc "$SERVER__USE_CAPS_FOR_ID")|g" \
        -e "s|__SERVER__PREFETCH__|$(esc "$SERVER__PREFETCH")|g" \
        -e "s|__SERVER__PREFETCH_KEY__|$(esc "$SERVER__PREFETCH_KEY")|g" \
        -e "s|__SERVER__QNAME_MINIMISATION__|$(esc "$SERVER__QNAME_MINIMISATION")|g" \
        -e "s|__SERVER__MINIMAL_RESPONSES__|$(esc "$SERVER__MINIMAL_RESPONSES")|g" \
        -e "s|__SERVER__HIDE_IDENTITY__|$(esc "$SERVER__HIDE_IDENTITY")|g" \
        -e "s|__SERVER__HIDE_VERSION__|$(esc "$SERVER__HIDE_VERSION")|g" \
        -e "s|__SERVER__HARDEN_GLUE__|$(esc "$SERVER__HARDEN_GLUE")|g" \
        -e "s|__SERVER__HARDEN_DNSSEC_STRIPPED__|$(esc "$SERVER__HARDEN_DNSSEC_STRIPPED")|g" \
        -e "s|__SERVER__HARDEN_REFERRAL_PATH__|$(esc "$SERVER__HARDEN_REFERRAL_PATH")|g" \
        -e "s|__SERVER__HARDEN_ALGO_DOWNGRADE__|$(esc "$SERVER__HARDEN_ALGO_DOWNGRADE")|g" \
        -e "s|__SERVER__CACHE_MIN_TTL__|$(esc "$SERVER__CACHE_MIN_TTL")|g" \
        -e "s|__SERVER__CACHE_MAX_TTL__|$(esc "$SERVER__CACHE_MAX_TTL")|g" \
        -e "s|__SERVER__MSG_CACHE_SIZE__|$(esc "$SERVER__MSG_CACHE_SIZE")|g" \
        -e "s|__SERVER__RRSET_CACHE_SIZE__|$(esc "$SERVER__RRSET_CACHE_SIZE")|g" \
        -e "s|__SERVER__UNWANTED_REPLY_THRESHOLD__|$(esc "$SERVER__UNWANTED_REPLY_THRESHOLD")|g" \
        "$TEMPLATE" > "$CONF"
fi

if [ -n "$SERVER__AUTO_TRUST_ANCHOR_FILE" ] && [ ! -f "$SERVER__AUTO_TRUST_ANCHOR_FILE" ]; then
    unbound-anchor -a "$SERVER__AUTO_TRUST_ANCHOR_FILE"
fi

if [ -n "$FORWARD_ZONE__FORWARD_ADDR" ]; then
    FORWARD_ADDR_HOST="$FORWARD_ZONE__FORWARD_ADDR"
    FORWARD_ADDR_PORT=""
    if printf '%s' "$FORWARD_ZONE__FORWARD_ADDR" | grep -q '@'; then
        FORWARD_ADDR_HOST="${FORWARD_ZONE__FORWARD_ADDR%@*}"
        FORWARD_ADDR_PORT="${FORWARD_ZONE__FORWARD_ADDR#*@}"
    fi

    if printf '%s' "$FORWARD_ADDR_HOST" | grep -Eq '^[0-9.]+$|^[0-9a-fA-F:]+$'; then
        FORWARD_ADDR_RESOLVED_HOST="$FORWARD_ADDR_HOST"
    else
        FORWARD_ADDR_RESOLVED_HOST="$(getent hosts "$FORWARD_ADDR_HOST" | awk 'NR==1{print $1}')"
        if [ -z "$FORWARD_ADDR_RESOLVED_HOST" ]; then
            echo "unable to resolve forward-addr host: $FORWARD_ADDR_HOST" >&2
            exit 1
        fi
    fi

    if [ -n "$FORWARD_ADDR_PORT" ]; then
        FORWARD_ADDR_RESOLVED="${FORWARD_ADDR_RESOLVED_HOST}@${FORWARD_ADDR_PORT}"
    else
        FORWARD_ADDR_RESOLVED="${FORWARD_ADDR_RESOLVED_HOST}"
    fi

    cat >> "$CONF" <<EOF

forward-zone:
    name: "${FORWARD_ZONE__NAME}"
    forward-addr: ${FORWARD_ADDR_RESOLVED}
    forward-tls-upstream: ${FORWARD_ZONE__FORWARD_TLS_UPSTREAM}
EOF
fi

exec /usr/sbin/unbound -d -c "$CONF"
